### ISSUE TITLE
Getting deadlock issues when mocking in specs (3.3.0)

### ISSUE THREAD

**Issue by ahorner** [rspec/rspec-core#1994]
After upgrading to 3.3.0, I started seeing a handful of consistent spec failures.

- Installed through `rspec-rails` version 3.3.0
- Rails version 4.2.1
- Using `infer_spec_type_from_file_location!`

The failing specs have the following in common: They are in the `spec/policies` directory, and use the `expect_any_instance_of` or `allow_any_instance_of` methods (both seem to run into the same issue).

The failures manifest as such:
```
8) EventPolicy#overbooked? when any Assignment is overbooked should be overbooked
     Failure/Error: it { is_expected.to be_overbooked }
     ThreadError:
       deadlock; recursive locking
     # ./app/policies/event_policy.rb:29:in `block in overbooked?'
     # ./app/policies/event_policy.rb:28:in `any?'
     # ./app/policies/event_policy.rb:28:in `overbooked?'
     # ./spec/policies/event_policy_spec.rb:35:in `block (4 levels) in <top (required)>'

  9) BookingPolicy#ready_for_approval? when there are events and they are ready for approval should be ready for approval
     Failure/Error: it { is_expected.to be_ready_for_approval }
     ThreadError:
       deadlock; recursive locking
     # ./app/policies/booking_policy.rb:8:in `block in ready_for_approval?'
     # ./app/policies/booking_policy.rb:8:in `each'
     # ./app/policies/booking_policy.rb:8:in `all?'
     # ./app/policies/booking_policy.rb:8:in `ready_for_approval?'
     # ./spec/policies/booking_policy_spec.rb:23:in `block (5 levels) in <top (required)>'
```

**Comment by myronmarston** [comment]
RSpec doesn't spin up any threads so I'd be surprised if it's causing this...although an internal change may have allowed a deadlock problem to surface.  Is there any way you can provide a reproducible example of this?

If you can't provide that, can you run your specs with `-b` to get the full backtrace and past that here?

**Comment by ahorner** [comment]
Backtraces here; looks like it's an issue in rspec-mocks.
```
Failures:

  1) BookingPolicy#ready_for_approval? when there are events but they are not ready for approval should not be ready for approval
     Failure/Error: it { is_expected.to_not be_ready_for_approval }
     ThreadError:
       deadlock; recursive locking
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `synchronize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/test_double.rb:111:in `__mock_proxy'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/test_double.rb:29:in `null_object?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_double.rb:8:in `respond_to?'
     # /Users/ahorner/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/delegate.rb:105:in `respond_to_missing?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-rails-3.3.0/lib/rspec/rails/active_record.rb:12:in `respond_to?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-rails-3.3.0/lib/rspec/rails/active_record.rb:12:in `block (2 levels) in initialize_activerecord_configuration'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:103:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:103:in `block in initialize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:102:in `each'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:102:in `initialize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:160:in `new'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:160:in `proxy_not_found_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `block (2 levels) in proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `fetch'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `block in proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `synchronize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/any_instance/recorder.rb:104:in `playback!'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/any_instance/recorder.rb:231:in `block in observe!'
     # ./app/policies/booking_policy.rb:8:in `block in ready_for_approval?'
     # ./app/policies/booking_policy.rb:8:in `each'
     # ./app/policies/booking_policy.rb:8:in `all?'
     # ./app/policies/booking_policy.rb:8:in `ready_for_approval?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/matchers/built_in/be.rb:236:in `predicate_matches?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/matchers/built_in/be.rb:194:in `does_not_match?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:78:in `does_not_match?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:72:in `block in handle_matcher'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:70:in `handle_matcher'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/expectation_target.rb:67:in `not_to'
     # ./spec/policies/booking_policy_spec.rb:30:in `block (5 levels) in <top (required)>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-rails-3.3.0/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:203:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:555:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:521:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:89:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/rspec:23:in `load'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/rspec:23:in `<main>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/ruby_executable_hooks:15:in `eval'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/ruby_executable_hooks:15:in `<main>'

  2) BookingPolicy#ready_for_approval? when there are events and they are ready for approval should be ready for approval
     Failure/Error: it { is_expected.to be_ready_for_approval }
     ThreadError:
       deadlock; recursive locking
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `synchronize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/test_double.rb:111:in `__mock_proxy'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/test_double.rb:29:in `null_object?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_double.rb:8:in `respond_to?'
     # /Users/ahorner/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/delegate.rb:105:in `respond_to_missing?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-rails-3.3.0/lib/rspec/rails/active_record.rb:12:in `respond_to?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-rails-3.3.0/lib/rspec/rails/active_record.rb:12:in `block (2 levels) in initialize_activerecord_configuration'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:103:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:103:in `block in initialize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:102:in `each'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:102:in `initialize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:160:in `new'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:160:in `proxy_not_found_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `block (2 levels) in proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `fetch'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `block in proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `synchronize'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `proxy_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/any_instance/recorder.rb:104:in `playback!'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-mocks-3.3.0/lib/rspec/mocks/any_instance/recorder.rb:231:in `block in observe!'
     # ./app/policies/booking_policy.rb:8:in `block in ready_for_approval?'
     # ./app/policies/booking_policy.rb:8:in `each'
     # ./app/policies/booking_policy.rb:8:in `all?'
     # ./app/policies/booking_policy.rb:8:in `ready_for_approval?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/matchers/built_in/be.rb:236:in `predicate_matches?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/matchers/built_in/be.rb:188:in `matches?'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-expectations-3.3.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/policies/booking_policy_spec.rb:23:in `block (5 levels) in <top (required)>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-rails-3.3.0/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:273:in `call'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:203:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:555:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:521:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `map'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:89:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/rspec:23:in `load'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/rspec:23:in `<main>'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/ruby_executable_hooks:15:in `eval'
     # /Users/ahorner/.rvm/gems/ruby-2.2.2@test-app/bin/ruby_executable_hooks:15:in `<main>'

Finished in 0.07235 seconds (files took 6.5 seconds to load)
3 examples, 2 failures
```
