### ISSUE TITLE
Odd output for "Caused by"

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-core#2155]
I'm seeing some confusing output when a spec fails after upgrading from `3.3` 5o `3.4`. For the most part everything is the same, but the new `Caused by` section says `Errno::ECONNREFUSED`. Is there some setting I'm missing?
```
Failures:

  1) Admin::AdminController#ensure_admin! when the user is an admin does nothing
     Failure/Error: expect(flash[:error]).not_to be_nil
     
       expected: not nil
            got: nil
     # ./spec/controllers/admin/admin_controller/ensure_admin_bang_spec.rb:22:in `block (3 levels) in <module:Admin>'
     # /home/fletch/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
     # /home/fletch/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
     # /home/fletch/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
     # /home/fletch/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
     # /home/fletch/.rvm/gems/ruby-2.1.7/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # Errno::ECONNREFUSED:
     #   Connection refused - connect(2) for "127.0.0.1" port 8989
     #   /home/fletch/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
```
