### ISSUE TITLE
on long strings, rspec does not display the part of the string that does not match

### ISSUE THREAD

**Issue by kevinburkeomg** [rspec/rspec-core#2535]
I'm trying to track down an error in a flaky test. Unfortunately the string output presented by rspec does not display the problem.

The following test should be enough to demonstrate the problem:

```ruby
describe 'a long string' do
  it 'shows the right part of the diff' do
    got = "a"*100 + "Z" + "a"*100
    want = "a" * (1 + 100*2)
    expect(got).to eq(want)
  end
end
```

Yields the following output:

```
Failures:

  1) a long string shows the right part of the diff
     Failure/Error: expect(got).to eq(want)

       expected: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
            got: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

       (compared using ==)
     # ./longstring_spec.rb:5:in `block (2 levels) in <top (required)>'
```

The strings displayed by rspec are identical; the diff is in the truncated part. If the string is any shorter, the diff appears correctly.

Running on a Mac in iTerm2.

```
$ rspec --version
RSpec 3.7
  - rspec-core 3.7.1
  - rspec-expectations 3.7.0
  - rspec-mocks 3.7.0
  - rspec-support 3.7.1
```

**Comment by myronmarston** [comment]
Thanks for reporting this!

It's unfortunate we're not printing the differing part of the string.  I think RSpec's output could get much better with a differ designed for RSpec itself, that would give better snippets that highlights the differences.  That's a feature I'd like to see us gain in the future.

In the meantime, to fix your issue, I think we can add some conditional logic to not truncate the string like that if the expected/got values are the same.  Want to take a stab at that?

**Comment by kevinburkeomg** [comment]
> Want to take a stab at that?

Apologies - I am not likely to have time to investigate/test/produce a proper patch :( Just wanted to alert you to this issue as is.

**Comment by kevinburkeomg** [comment]
Ah, this is a dupe of https://github.com/rspec/rspec-expectations/issues/991.

The suggestion there is to set `RSpec::Support::ObjectFormatter.default_instance.max_formatted_output_length` to a high enough value.

**Comment by kevinburkeomg** [comment]
Otherwise it might be difficult.

```ruby
        def failure_message
          "\nexpected: #{expected_formatted}\n     got: #{actual_formatted}\n\n(compared using ==)\n"
        end
```

Each of expected_formatted and actual_formatted formats the string independently, so we'd need to do something to check whether those strings are identical, then call the same method again with different parameters or a different method in the hopes of getting a non-identical string.

**Comment by benoittgt** [comment]
I will probably try to work on this. 

What I would like to do is display something like

```
Failures:

  1) a long string shows the right part of the diff
     Failure/Error: expect(got).to eq(want)

       expected: "...aaaaaaaa..."
            got: "...aaaabaaa..."

       (compared using ==)
     # ./longstring_spec.rb:5:in `block (2 levels) in <top (required)>'
```

But I have few issues:
- Is it limited to strings?
- What happens when there are multiple differences?
- Is it an option to set?
