### ISSUE TITLE
rspec testsuite error with ruby3.4.0dev

### ISSUE THREAD

**Issue by mtasaka** [rspec/rspec-core#3123]
With using ruby3.4.0dev ( `ruby 3.4.0dev (2024-11-15 master 51666c827b) +PRISM [x86_64-linux]` ),
executing rspec-core 3.13.2 rspec testsuite causes errors like:

```
Failures:

  1) RSpec::Core::DRbOptions DRB args with tags leaves inclusion tags with values intact
     Failure/Error: @example_group_instance.instance_exec(*args, &block)

     RuntimeError:
       Warnings were generated: /builddir/build/BUILD/rubygem-rspec-core-3.13.2-build/rspec-core-3.13.2/lib/rspec/core/drb.rb:95: warning: warning: string returned by :tag.to_s will be frozen in the future
     # ./spec/spec_helper.rb:57:in 'CommonHelpers#without_env_vars'
     # ./spec/support/config_options_helper.rb:4:in 'block in <module:ConfigOptionsHelper>'
     # ./spec/support/isolated_home_directory.rb:13:in 'block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:46:in 'CommonHelpers#with_env_vars'
     # ./spec/support/isolated_home_directory.rb:12:in 'block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:57:in 'CommonHelpers#without_env_vars'
     # ./spec/support/isolated_home_directory.rb:11:in 'block (3 levels) in <top (required)>'
     # ./spec/support/isolated_home_directory.rb:7:in 'block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:65:in 'CommonHelpers#handle_current_dir_change'
     # ./spec/spec_helper.rb:75:in 'block (2 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:16:in 'block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in 'block (2 levels) in <top (required)>'

  2) RSpec::Core::DRbOptions DRB args with tags includes the inclusion tags with values
     Failure/Error: @example_group_instance.instance_exec(*args, &block)

     RuntimeError:
       Warnings were generated: /builddir/build/BUILD/rubygem-rspec-core-3.13.2-build/rspec-core-3.13.2/lib/rspec/core/drb.rb:95: warning: warning: string returned by :tag.to_s will be frozen in the future
     # ./spec/spec_helper.rb:57:in 'CommonHelpers#without_env_vars'
     # ./spec/support/config_options_helper.rb:4:in 'block in <module:ConfigOptionsHelper>'
     # ./spec/support/isolated_home_directory.rb:13:in 'block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:46:in 'CommonHelpers#with_env_vars'
     # ./spec/support/isolated_home_directory.rb:12:in 'block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:57:in 'CommonHelpers#without_env_vars'
     # ./spec/support/isolated_home_directory.rb:11:in 'block (3 levels) in <top (required)>'
     # ./spec/support/isolated_home_directory.rb:7:in 'block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:65:in 'CommonHelpers#handle_current_dir_change'
     # ./spec/spec_helper.rb:75:in 'block (2 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:16:in 'block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in 'block (2 levels) in <top (required)>'

Finished in 7.94 seconds (files took 0.44011 seconds to load)
2234 examples, 2 failures, 6 pending
```

This is probably due to https://github.com/ruby/ruby/commit/6deeec5d459ecff5ec4628523b14ac7379fd942e
