### ISSUE TITLE
Empty unnamed example raises confusing exception and generates invalid output

### ISSUE THREAD

**Issue by Ragmaanir** [rspec/rspec-core#585]
Hi,

when running:

``` ruby
describe 'issue: error when examples with no title and expectations' do
    it{  }
end
```

with rspec 2.9.0 i get:

```
issue: error when examples with no title and expectations

Failures:

  1) issue: error when examples with no title and expectations 
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `strip' for nil:NilClass
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/formatters/documentation_formatter.rb:50:in `passed_output'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/formatters/documentation_formatter.rb:27:in `example_passed'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:98:in `block in notify'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:97:in `each'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:97:in `notify'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:63:in `example_passed'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example.rb:205:in `finish'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example.rb:105:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:10:in `block in autorun'

Finished in 0.00037 seconds
2 examples, 1 failure
```

When i run:

``` ruby
describe 'issues' do
    describe 'issue: error when examples with no title and expectations' do
        it{  }
    end
end
```

the output is even more confusing:

```
issues
  issue: error when examples with no title and expectations
  issue: error when examples with no title and expectations

Failures:

  1) issues issue: error when examples with no title and expectations 
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `strip' for nil:NilClass
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/formatters/documentation_formatter.rb:50:in `passed_output'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/formatters/documentation_formatter.rb:27:in `example_passed'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:98:in `block in notify'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:97:in `each'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:97:in `notify'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:63:in `example_passed'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example.rb:205:in `finish'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example.rb:105:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:10:in `block in autorun'

  2) issues issue: error when examples with no title and expectations 
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `strip' for nil:NilClass
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/formatters/documentation_formatter.rb:50:in `passed_output'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/formatters/documentation_formatter.rb:27:in `example_passed'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:98:in `block in notify'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:97:in `each'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:97:in `notify'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:63:in `example_passed'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example.rb:205:in `finish'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example.rb:105:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/local/lib/ruby/gems/1.9.1/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:10:in `block in autorun'

Finished in 0.00059 seconds
3 examples, 2 failures
```

Even thought there actually is just one example the output says there are 3.

When i run:

``` ruby
describe 'issues' do
    it{ true.should be_true }
end
```

or

``` ruby
describe 'issues' do
    it(:passes){  }
end
```

everything passes.

EDIT: Invalid output is also generated when one raises in a before block (but the exception is ok):

``` ruby
describe 'issues' do
    describe 'issue: when raising in before' do
        before{ raise }
        it{ :a.should == :a }
    end
end
```
